### ISSUE TITLE
Haml

### ISSUE THREAD

**Issue by dronov** [samuels410/helpalife#3]
I suggest to switch all erb views to Haml. They will be more readable, easier to use and well-looking.  :)

**Comment by samuels410** [comment]
@dronov  That will become a pain full process thats the way I think .
I thing we can slowly replace the while the new developments. So we can concentrate on  bug fixes and grooming the product.

**Comment by dronov** [comment]
@samuels410 I have such expirience - most of troubles was almost with tabulations. [This service](http://htmltohaml.com/) works well, I use it every day.
Got it, thanks.
